extends:
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "next/core-web-vitals"
  - "prettier"

plugins:
  - import

settings:
  import/core-modules:
    - windi.css
  import/resolver:
    node:
      extensions:
        - .ts

rules:
  sort-imports: 0
  import/order:
    - 2
    - alphabetize:
        order: asc
      newlines-between: always
      pathGroups:
        - pattern: "@alias/**"
          group: parent
          position: before
  react/jsx-sort-props:
    - 1
    - shorthandLast: true
      ignoreCase: true
      reservedFirst: true
