import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Card } from 'antd'
import { useGetPageByTitleQuery } from '../generated/graphql'

const Home: NextPage = () => {
  const { data } = useGetPageByTitleQuery({ variables: { title: 'Home' }})

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card title={data?.pageByTitle?.title ?? "undefind"}>
          <div dangerouslySetInnerHTML={{ __html: data?.pageByTitle?.bodyHtml ?? ""}} />
        </Card>
        <Button type="primary">Button</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
