import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import { Button, Card } from 'antd'
import { useGetPageByTitleQuery } from '../../generated/graphql'

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
  const { title } = context.params!;
  const joinedTitle = (title as string[]).join("/")
  return {
    props: {
      title: joinedTitle
    }
  }
}

const Page: NextPage<Awaited<ReturnType<typeof getServerSideProps>>["props"]> = ({ title }) => {
  const { data } = useGetPageByTitleQuery({ variables: { title }})

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card title={data?.pageByTitle?.title ?? "undefined"}>
          <div dangerouslySetInnerHTML={{ __html: data?.pageByTitle?.bodyHtml ?? ""}} />
        </Card>
        <Button type="primary">Button</Button>
      </main>
    </div>
  )
}

export default Page
